export const gameState = {
    music: document.getElementById('music'),
    recordButton: document.getElementById('recordButton'),
    stopRecordingButton: document.getElementById('stopRecordingButton'),
    playButton: document.getElementById('playButton'),
    musicFileInput: document.getElementById('musicFile'),
    chartFileInput: document.getElementById('chartFile'),
    volumeControl: document.getElementById('volumeControl'),
    lanes: ['A', 'S', 'D', 'F'],
    notes: [],
    recording: false,
    playing: false,
    chartData: [],
    originalChartData: [],
    activeHoldNotes: [],
    holdCheckpoints: [],
    startTime: 0,
    combo: 0,
    hp: 500,
    fallSpeed: 7.5,
    spawnOffset: 1200,
    keysPressed: {},
    keysHit: {},
    holdStartTimes: {},
    gameStopped: false,
};
